# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: datatypes.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'datatypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61tatypes.proto\",\n\rSimpleMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"%\n\x12SimpleMessageClone\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x1c\n\x0bTemperature\x12\r\n\x05value\x18\x01 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datatypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMPLEMESSAGE']._serialized_start=19
  _globals['_SIMPLEMESSAGE']._serialized_end=63
  _globals['_SIMPLEMESSAGECLONE']._serialized_start=65
  _globals['_SIMPLEMESSAGECLONE']._serialized_end=102
  _globals['_TEMPERATURE']._serialized_start=104
  _globals['_TEMPERATURE']._serialized_end=132
# @@protoc_insertion_point(module_scope)
